### ISSUE TITLE
Decimals issues on UST Wormhole

### ISSUE THREAD

**Issue by mwamedacen** [sameepsi/quickswap-default-token-list#88]
The current decimals set for UST Wormhole is wrong. We should have 6 instead of 18.

Compare: [token list](https://github.com/sameepsi/quickswap-default-token-list/blob/master/src/tokens/mainnet.json#L790) vs [actual contract](https://polygonscan.com/token/0xE6469Ba6D2fD6130788E0eA9C0a0515900563b59)

---

Also, it looks like the most liquid UST token on polygon is [0x6925...875f](https://polygonscan.com/token/0x692597b009d13c4049a947cab2239b7d6517875f) (which is encoded with 18 decimals) not [0xE646...3b59](https://polygonscan.com/address/0xE6469Ba6D2fD6130788E0eA9C0a0515900563b59) (the one you have in token list)

**Comment by sameepsi** [comment]
Thanks for pointing it out.

To address your other issue, the token was recently updated after the request from LUNA team
